project:
  type: website

website:
  title: "The ICTML Project"
  
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Install
        href: install.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/ictml-project/ictml.org/
        aria-label: GitHub
        
  search: 
    location: navbar
    type: overlay
    
  repo-url: https://github.com/ictml-project/ictml.org/
  repo-actions: [source, edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
