project:
  type: website
  output-dir: ../_site

website:
  title: "ICTML"
  favicon: assets/ictml.svg
  
  navbar:
    logo: assets/ictml.svg
    title: " "
    left:
      - text: Home
        href: index.qmd
      # - text: Install
      #   href: install.qmd
      - software.qmd
      - team.qmd
    right:
      - icon: github
        href: https://github.com/ictml-project/ictml.org/
        aria-label: GitHub
        
  search: 
    location: navbar
    type: overlay
    
  repo-url: https://github.com/ictml-project/ictml.org/
  repo-actions: [source, edit, issue]

format:
  html:
    theme:
      light: assets/ictml-light.scss
      dark: assets/ictml-dark.scss
    css: assets/ictml.css
    toc: true
